// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/myorg/employee/message/employee-management.proto

package com.myorg.employee.message;

public interface CreateEmployeeDepartmentCmdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.myorg.employee.message.CreateEmployeeDepartmentCmd)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string employeeId = 1;</code>
   */
  java.lang.String getEmployeeId();
  /**
   * <code>string employeeId = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmployeeIdBytes();

  /**
   * <code>string departmentId = 2;</code>
   */
  java.lang.String getDepartmentId();
  /**
   * <code>string departmentId = 2;</code>
   */
  com.google.protobuf.ByteString
      getDepartmentIdBytes();
}
