// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/myorg/employee/message/employee-management.proto

package com.myorg.employee.message;

public interface DeleteGenderCmdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.myorg.employee.message.DeleteGenderCmd)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
