// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/myorg/employee/message/employee-management.proto

package com.myorg.employee.message;

public interface DepartmentVoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.myorg.employee.message.DepartmentVo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string desc = 3;</code>
   */
  java.lang.String getDesc();
  /**
   * <code>string desc = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescBytes();
}
