// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/myorg/employee/message/employee-management.proto

package com.myorg.employee.message;

/**
 * Protobuf type {@code com.myorg.employee.message.EmployeeDepartmentListVo}
 */
public  final class EmployeeDepartmentListVo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.myorg.employee.message.EmployeeDepartmentListVo)
    EmployeeDepartmentListVoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EmployeeDepartmentListVo.newBuilder() to construct.
  private EmployeeDepartmentListVo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EmployeeDepartmentListVo() {
    items_ = java.util.Collections.emptyList();
    pagingState_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EmployeeDepartmentListVo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              items_ = new java.util.ArrayList<com.myorg.employee.message.EmployeeDepartmentVo>();
              mutable_bitField0_ |= 0x00000001;
            }
            items_.add(
                input.readMessage(com.myorg.employee.message.EmployeeDepartmentVo.parser(), extensionRegistry));
            break;
          }
          case 16: {

            hasMore_ = input.readBool();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            pagingState_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        items_ = java.util.Collections.unmodifiableList(items_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.myorg.employee.message.EmployeeManagement.internal_static_com_myorg_employee_message_EmployeeDepartmentListVo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.myorg.employee.message.EmployeeManagement.internal_static_com_myorg_employee_message_EmployeeDepartmentListVo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.myorg.employee.message.EmployeeDepartmentListVo.class, com.myorg.employee.message.EmployeeDepartmentListVo.Builder.class);
  }

  private int bitField0_;
  public static final int ITEMS_FIELD_NUMBER = 1;
  private java.util.List<com.myorg.employee.message.EmployeeDepartmentVo> items_;
  /**
   * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
   */
  public java.util.List<com.myorg.employee.message.EmployeeDepartmentVo> getItemsList() {
    return items_;
  }
  /**
   * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
   */
  public java.util.List<? extends com.myorg.employee.message.EmployeeDepartmentVoOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
   */
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
   */
  public com.myorg.employee.message.EmployeeDepartmentVo getItems(int index) {
    return items_.get(index);
  }
  /**
   * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
   */
  public com.myorg.employee.message.EmployeeDepartmentVoOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  public static final int HASMORE_FIELD_NUMBER = 2;
  private boolean hasMore_;
  /**
   * <code>bool hasMore = 2;</code>
   */
  public boolean getHasMore() {
    return hasMore_;
  }

  public static final int PAGINGSTATE_FIELD_NUMBER = 3;
  private volatile java.lang.Object pagingState_;
  /**
   * <code>string pagingState = 3;</code>
   */
  public java.lang.String getPagingState() {
    java.lang.Object ref = pagingState_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pagingState_ = s;
      return s;
    }
  }
  /**
   * <code>string pagingState = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPagingStateBytes() {
    java.lang.Object ref = pagingState_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pagingState_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(1, items_.get(i));
    }
    if (hasMore_ != false) {
      output.writeBool(2, hasMore_);
    }
    if (!getPagingStateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, pagingState_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, items_.get(i));
    }
    if (hasMore_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, hasMore_);
    }
    if (!getPagingStateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, pagingState_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.myorg.employee.message.EmployeeDepartmentListVo)) {
      return super.equals(obj);
    }
    com.myorg.employee.message.EmployeeDepartmentListVo other = (com.myorg.employee.message.EmployeeDepartmentListVo) obj;

    if (!getItemsList()
        .equals(other.getItemsList())) return false;
    if (getHasMore()
        != other.getHasMore()) return false;
    if (!getPagingState()
        .equals(other.getPagingState())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    hash = (37 * hash) + HASMORE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasMore());
    hash = (37 * hash) + PAGINGSTATE_FIELD_NUMBER;
    hash = (53 * hash) + getPagingState().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.myorg.employee.message.EmployeeDepartmentListVo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.myorg.employee.message.EmployeeDepartmentListVo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.myorg.employee.message.EmployeeDepartmentListVo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.myorg.employee.message.EmployeeDepartmentListVo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.myorg.employee.message.EmployeeDepartmentListVo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.myorg.employee.message.EmployeeDepartmentListVo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.myorg.employee.message.EmployeeDepartmentListVo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.myorg.employee.message.EmployeeDepartmentListVo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.myorg.employee.message.EmployeeDepartmentListVo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.myorg.employee.message.EmployeeDepartmentListVo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.myorg.employee.message.EmployeeDepartmentListVo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.myorg.employee.message.EmployeeDepartmentListVo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.myorg.employee.message.EmployeeDepartmentListVo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.myorg.employee.message.EmployeeDepartmentListVo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.myorg.employee.message.EmployeeDepartmentListVo)
      com.myorg.employee.message.EmployeeDepartmentListVoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.myorg.employee.message.EmployeeManagement.internal_static_com_myorg_employee_message_EmployeeDepartmentListVo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.myorg.employee.message.EmployeeManagement.internal_static_com_myorg_employee_message_EmployeeDepartmentListVo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.myorg.employee.message.EmployeeDepartmentListVo.class, com.myorg.employee.message.EmployeeDepartmentListVo.Builder.class);
    }

    // Construct using com.myorg.employee.message.EmployeeDepartmentListVo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getItemsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        itemsBuilder_.clear();
      }
      hasMore_ = false;

      pagingState_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.myorg.employee.message.EmployeeManagement.internal_static_com_myorg_employee_message_EmployeeDepartmentListVo_descriptor;
    }

    @java.lang.Override
    public com.myorg.employee.message.EmployeeDepartmentListVo getDefaultInstanceForType() {
      return com.myorg.employee.message.EmployeeDepartmentListVo.getDefaultInstance();
    }

    @java.lang.Override
    public com.myorg.employee.message.EmployeeDepartmentListVo build() {
      com.myorg.employee.message.EmployeeDepartmentListVo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.myorg.employee.message.EmployeeDepartmentListVo buildPartial() {
      com.myorg.employee.message.EmployeeDepartmentListVo result = new com.myorg.employee.message.EmployeeDepartmentListVo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
      result.hasMore_ = hasMore_;
      result.pagingState_ = pagingState_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.myorg.employee.message.EmployeeDepartmentListVo) {
        return mergeFrom((com.myorg.employee.message.EmployeeDepartmentListVo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.myorg.employee.message.EmployeeDepartmentListVo other) {
      if (other == com.myorg.employee.message.EmployeeDepartmentListVo.getDefaultInstance()) return this;
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      if (other.getHasMore() != false) {
        setHasMore(other.getHasMore());
      }
      if (!other.getPagingState().isEmpty()) {
        pagingState_ = other.pagingState_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.myorg.employee.message.EmployeeDepartmentListVo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.myorg.employee.message.EmployeeDepartmentListVo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.myorg.employee.message.EmployeeDepartmentVo> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        items_ = new java.util.ArrayList<com.myorg.employee.message.EmployeeDepartmentVo>(items_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.myorg.employee.message.EmployeeDepartmentVo, com.myorg.employee.message.EmployeeDepartmentVo.Builder, com.myorg.employee.message.EmployeeDepartmentVoOrBuilder> itemsBuilder_;

    /**
     * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
     */
    public java.util.List<com.myorg.employee.message.EmployeeDepartmentVo> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
     */
    public com.myorg.employee.message.EmployeeDepartmentVo getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
     */
    public Builder setItems(
        int index, com.myorg.employee.message.EmployeeDepartmentVo value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
     */
    public Builder setItems(
        int index, com.myorg.employee.message.EmployeeDepartmentVo.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
     */
    public Builder addItems(com.myorg.employee.message.EmployeeDepartmentVo value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
     */
    public Builder addItems(
        int index, com.myorg.employee.message.EmployeeDepartmentVo value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
     */
    public Builder addItems(
        com.myorg.employee.message.EmployeeDepartmentVo.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
     */
    public Builder addItems(
        int index, com.myorg.employee.message.EmployeeDepartmentVo.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends com.myorg.employee.message.EmployeeDepartmentVo> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
     */
    public com.myorg.employee.message.EmployeeDepartmentVo.Builder getItemsBuilder(
        int index) {
      return getItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
     */
    public com.myorg.employee.message.EmployeeDepartmentVoOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
     */
    public java.util.List<? extends com.myorg.employee.message.EmployeeDepartmentVoOrBuilder> 
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
     */
    public com.myorg.employee.message.EmployeeDepartmentVo.Builder addItemsBuilder() {
      return getItemsFieldBuilder().addBuilder(
          com.myorg.employee.message.EmployeeDepartmentVo.getDefaultInstance());
    }
    /**
     * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
     */
    public com.myorg.employee.message.EmployeeDepartmentVo.Builder addItemsBuilder(
        int index) {
      return getItemsFieldBuilder().addBuilder(
          index, com.myorg.employee.message.EmployeeDepartmentVo.getDefaultInstance());
    }
    /**
     * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
     */
    public java.util.List<com.myorg.employee.message.EmployeeDepartmentVo.Builder> 
         getItemsBuilderList() {
      return getItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.myorg.employee.message.EmployeeDepartmentVo, com.myorg.employee.message.EmployeeDepartmentVo.Builder, com.myorg.employee.message.EmployeeDepartmentVoOrBuilder> 
        getItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.myorg.employee.message.EmployeeDepartmentVo, com.myorg.employee.message.EmployeeDepartmentVo.Builder, com.myorg.employee.message.EmployeeDepartmentVoOrBuilder>(
                items_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }

    private boolean hasMore_ ;
    /**
     * <code>bool hasMore = 2;</code>
     */
    public boolean getHasMore() {
      return hasMore_;
    }
    /**
     * <code>bool hasMore = 2;</code>
     */
    public Builder setHasMore(boolean value) {
      
      hasMore_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool hasMore = 2;</code>
     */
    public Builder clearHasMore() {
      
      hasMore_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object pagingState_ = "";
    /**
     * <code>string pagingState = 3;</code>
     */
    public java.lang.String getPagingState() {
      java.lang.Object ref = pagingState_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pagingState_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pagingState = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPagingStateBytes() {
      java.lang.Object ref = pagingState_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pagingState_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pagingState = 3;</code>
     */
    public Builder setPagingState(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pagingState_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pagingState = 3;</code>
     */
    public Builder clearPagingState() {
      
      pagingState_ = getDefaultInstance().getPagingState();
      onChanged();
      return this;
    }
    /**
     * <code>string pagingState = 3;</code>
     */
    public Builder setPagingStateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pagingState_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.myorg.employee.message.EmployeeDepartmentListVo)
  }

  // @@protoc_insertion_point(class_scope:com.myorg.employee.message.EmployeeDepartmentListVo)
  private static final com.myorg.employee.message.EmployeeDepartmentListVo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.myorg.employee.message.EmployeeDepartmentListVo();
  }

  public static com.myorg.employee.message.EmployeeDepartmentListVo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmployeeDepartmentListVo>
      PARSER = new com.google.protobuf.AbstractParser<EmployeeDepartmentListVo>() {
    @java.lang.Override
    public EmployeeDepartmentListVo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EmployeeDepartmentListVo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EmployeeDepartmentListVo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmployeeDepartmentListVo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.myorg.employee.message.EmployeeDepartmentListVo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

