// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/myorg/employee/message/employee-management.proto

package com.myorg.employee.message;

public final class EmployeeManagement {
  private EmployeeManagement() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_UserVo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_UserVo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_UserListVo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_UserListVo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_CreateUserCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_CreateUserCmd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_UpdateUserCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_UpdateUserCmd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_DeleteUserCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_DeleteUserCmd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_RetrieveUserCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_RetrieveUserCmd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_GenderVo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_GenderVo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_GenderListVo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_GenderListVo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_CreateGenderCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_CreateGenderCmd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_UpdateGenderCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_UpdateGenderCmd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_DeleteGenderCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_DeleteGenderCmd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_RetrieveGenderCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_RetrieveGenderCmd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_EmployeeVo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_EmployeeVo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_EmployeeListVo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_EmployeeListVo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_CreateEmployeeCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_CreateEmployeeCmd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_UpdateEmployeeCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_UpdateEmployeeCmd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_DeleteEmployeeCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_DeleteEmployeeCmd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_RetrieveEmployeeCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_RetrieveEmployeeCmd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_DepartmentVo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_DepartmentVo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_DepartmentListVo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_DepartmentListVo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_CreateDepartmentCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_CreateDepartmentCmd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_UpdateDepartmentCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_UpdateDepartmentCmd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_DeleteDepartmentCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_DeleteDepartmentCmd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_RetrieveDepartmentCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_RetrieveDepartmentCmd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_EmployeeDepartmentVo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_EmployeeDepartmentVo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_EmployeeDepartmentListVo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_EmployeeDepartmentListVo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_CreateEmployeeDepartmentCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_CreateEmployeeDepartmentCmd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_UpdateEmployeeDepartmentCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_UpdateEmployeeDepartmentCmd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_DeleteEmployeeDepartmentCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_DeleteEmployeeDepartmentCmd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_myorg_employee_message_RetrieveEmployeeDepartmentCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_myorg_employee_message_RetrieveEmployeeDepartmentCmd_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4com/myorg/employee/message/employee-ma" +
      "nagement.proto\022\032com.myorg.employee.messa" +
      "ge\032\037google/protobuf/timestamp.proto\032\025sca" +
      "lapb/scalapb.proto\"(\n\006UserVo\022\014\n\004name\030\001 \001" +
      "(\t\022\020\n\010password\030\002 \001(\t\"e\n\nUserListVo\0221\n\005it" +
      "ems\030\001 \003(\0132\".com.myorg.employee.message.U" +
      "serVo\022\017\n\007hasMore\030\002 \001(\010\022\023\n\013pagingState\030\003 " +
      "\001(\t\"/\n\rCreateUserCmd\022\014\n\004name\030\001 \001(\t\022\020\n\010pa" +
      "ssword\030\002 \001(\t\"/\n\rUpdateUserCmd\022\014\n\004name\030\001 " +
      "\001(\t\022\020\n\010password\030\002 \001(\t\"\035\n\rDeleteUserCmd\022\014" +
      "\n\004name\030\001 \001(\t\"\037\n\017RetrieveUserCmd\022\014\n\004name\030" +
      "\001 \001(\t\"$\n\010GenderVo\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 " +
      "\001(\t\"i\n\014GenderListVo\0223\n\005items\030\001 \003(\0132$.com" +
      ".myorg.employee.message.GenderVo\022\017\n\007hasM" +
      "ore\030\002 \001(\010\022\023\n\013pagingState\030\003 \001(\t\"+\n\017Create" +
      "GenderCmd\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\"+\n\017U" +
      "pdateGenderCmd\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t" +
      "\"\035\n\017DeleteGenderCmd\022\n\n\002id\030\001 \001(\005\"\037\n\021Retri" +
      "eveGenderCmd\022\n\n\002id\030\001 \001(\005\"\214\001\n\nEmployeeVo\022" +
      "\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\0222\n\006gender\030\003 \001(" +
      "\0162\".com.myorg.employee.message.Gender\0220\n" +
      "\014employedDate\030\004 \001(\0132\032.google.protobuf.Ti" +
      "mestamp\"m\n\016EmployeeListVo\0225\n\005items\030\001 \003(\013" +
      "2&.com.myorg.employee.message.EmployeeVo" +
      "\022\017\n\007hasMore\030\002 \001(\010\022\023\n\013pagingState\030\003 \001(\t\"\223" +
      "\001\n\021CreateEmployeeCmd\022\n\n\002id\030\001 \001(\t\022\014\n\004name" +
      "\030\002 \001(\t\0222\n\006gender\030\003 \001(\0162\".com.myorg.emplo" +
      "yee.message.Gender\0220\n\014employedDate\030\004 \001(\013" +
      "2\032.google.protobuf.Timestamp\"\223\001\n\021UpdateE" +
      "mployeeCmd\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\0222\n\006" +
      "gender\030\003 \001(\0162\".com.myorg.employee.messag" +
      "e.Gender\0220\n\014employedDate\030\004 \001(\0132\032.google." +
      "protobuf.Timestamp\"\037\n\021DeleteEmployeeCmd\022" +
      "\n\n\002id\030\001 \001(\t\"!\n\023RetrieveEmployeeCmd\022\n\n\002id" +
      "\030\001 \001(\t\"6\n\014DepartmentVo\022\n\n\002id\030\001 \001(\t\022\014\n\004na" +
      "me\030\002 \001(\t\022\014\n\004desc\030\003 \001(\t\"q\n\020DepartmentList" +
      "Vo\0227\n\005items\030\001 \003(\0132(.com.myorg.employee.m" +
      "essage.DepartmentVo\022\017\n\007hasMore\030\002 \001(\010\022\023\n\013" +
      "pagingState\030\003 \001(\t\"=\n\023CreateDepartmentCmd" +
      "\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\014\n\004desc\030\003 \001(\t" +
      "\"=\n\023UpdateDepartmentCmd\022\n\n\002id\030\001 \001(\t\022\014\n\004n" +
      "ame\030\002 \001(\t\022\014\n\004desc\030\003 \001(\t\"!\n\023DeleteDepartm" +
      "entCmd\022\n\n\002id\030\001 \001(\t\"#\n\025RetrieveDepartment" +
      "Cmd\022\n\n\002id\030\001 \001(\t\"@\n\024EmployeeDepartmentVo\022" +
      "\022\n\nemployeeId\030\001 \001(\t\022\024\n\014departmentId\030\002 \001(" +
      "\t\"\201\001\n\030EmployeeDepartmentListVo\022?\n\005items\030" +
      "\001 \003(\01320.com.myorg.employee.message.Emplo" +
      "yeeDepartmentVo\022\017\n\007hasMore\030\002 \001(\010\022\023\n\013pagi" +
      "ngState\030\003 \001(\t\"G\n\033CreateEmployeeDepartmen" +
      "tCmd\022\022\n\nemployeeId\030\001 \001(\t\022\024\n\014departmentId" +
      "\030\002 \001(\t\"G\n\033UpdateEmployeeDepartmentCmd\022\022\n" +
      "\nemployeeId\030\001 \001(\t\022\024\n\014departmentId\030\002 \001(\t\"" +
      "G\n\033DeleteEmployeeDepartmentCmd\022\022\n\nemploy" +
      "eeId\030\001 \001(\t\022\024\n\014departmentId\030\002 \001(\t\"I\n\035Retr" +
      "ieveEmployeeDepartmentCmd\022\022\n\nemployeeId\030" +
      "\001 \001(\t\022\024\n\014departmentId\030\002 \001(\t*2\n\006Gender\022\022\n" +
      "\016UNKNOWN_GENDER\020\000\022\010\n\004MALE\020\001\022\n\n\006FEMALE\020\002B" +
      "7\n\032com.myorg.employee.messageB\022EmployeeM" +
      "anagementP\001\342?\002\020\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          scalapb.options.Scalapb.getDescriptor(),
        }, assigner);
    internal_static_com_myorg_employee_message_UserVo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_myorg_employee_message_UserVo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_UserVo_descriptor,
        new java.lang.String[] { "Name", "Password", });
    internal_static_com_myorg_employee_message_UserListVo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_myorg_employee_message_UserListVo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_UserListVo_descriptor,
        new java.lang.String[] { "Items", "HasMore", "PagingState", });
    internal_static_com_myorg_employee_message_CreateUserCmd_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_myorg_employee_message_CreateUserCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_CreateUserCmd_descriptor,
        new java.lang.String[] { "Name", "Password", });
    internal_static_com_myorg_employee_message_UpdateUserCmd_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_myorg_employee_message_UpdateUserCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_UpdateUserCmd_descriptor,
        new java.lang.String[] { "Name", "Password", });
    internal_static_com_myorg_employee_message_DeleteUserCmd_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_myorg_employee_message_DeleteUserCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_DeleteUserCmd_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_myorg_employee_message_RetrieveUserCmd_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_myorg_employee_message_RetrieveUserCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_RetrieveUserCmd_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_myorg_employee_message_GenderVo_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_myorg_employee_message_GenderVo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_GenderVo_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_com_myorg_employee_message_GenderListVo_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_myorg_employee_message_GenderListVo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_GenderListVo_descriptor,
        new java.lang.String[] { "Items", "HasMore", "PagingState", });
    internal_static_com_myorg_employee_message_CreateGenderCmd_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_myorg_employee_message_CreateGenderCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_CreateGenderCmd_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_com_myorg_employee_message_UpdateGenderCmd_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_myorg_employee_message_UpdateGenderCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_UpdateGenderCmd_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_com_myorg_employee_message_DeleteGenderCmd_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_myorg_employee_message_DeleteGenderCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_DeleteGenderCmd_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_myorg_employee_message_RetrieveGenderCmd_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_myorg_employee_message_RetrieveGenderCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_RetrieveGenderCmd_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_myorg_employee_message_EmployeeVo_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_myorg_employee_message_EmployeeVo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_EmployeeVo_descriptor,
        new java.lang.String[] { "Id", "Name", "Gender", "EmployedDate", });
    internal_static_com_myorg_employee_message_EmployeeListVo_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_myorg_employee_message_EmployeeListVo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_EmployeeListVo_descriptor,
        new java.lang.String[] { "Items", "HasMore", "PagingState", });
    internal_static_com_myorg_employee_message_CreateEmployeeCmd_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_myorg_employee_message_CreateEmployeeCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_CreateEmployeeCmd_descriptor,
        new java.lang.String[] { "Id", "Name", "Gender", "EmployedDate", });
    internal_static_com_myorg_employee_message_UpdateEmployeeCmd_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_myorg_employee_message_UpdateEmployeeCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_UpdateEmployeeCmd_descriptor,
        new java.lang.String[] { "Id", "Name", "Gender", "EmployedDate", });
    internal_static_com_myorg_employee_message_DeleteEmployeeCmd_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_myorg_employee_message_DeleteEmployeeCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_DeleteEmployeeCmd_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_myorg_employee_message_RetrieveEmployeeCmd_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_myorg_employee_message_RetrieveEmployeeCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_RetrieveEmployeeCmd_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_myorg_employee_message_DepartmentVo_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_myorg_employee_message_DepartmentVo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_DepartmentVo_descriptor,
        new java.lang.String[] { "Id", "Name", "Desc", });
    internal_static_com_myorg_employee_message_DepartmentListVo_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_myorg_employee_message_DepartmentListVo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_DepartmentListVo_descriptor,
        new java.lang.String[] { "Items", "HasMore", "PagingState", });
    internal_static_com_myorg_employee_message_CreateDepartmentCmd_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_com_myorg_employee_message_CreateDepartmentCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_CreateDepartmentCmd_descriptor,
        new java.lang.String[] { "Id", "Name", "Desc", });
    internal_static_com_myorg_employee_message_UpdateDepartmentCmd_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_com_myorg_employee_message_UpdateDepartmentCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_UpdateDepartmentCmd_descriptor,
        new java.lang.String[] { "Id", "Name", "Desc", });
    internal_static_com_myorg_employee_message_DeleteDepartmentCmd_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_com_myorg_employee_message_DeleteDepartmentCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_DeleteDepartmentCmd_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_myorg_employee_message_RetrieveDepartmentCmd_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_com_myorg_employee_message_RetrieveDepartmentCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_RetrieveDepartmentCmd_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_myorg_employee_message_EmployeeDepartmentVo_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_com_myorg_employee_message_EmployeeDepartmentVo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_EmployeeDepartmentVo_descriptor,
        new java.lang.String[] { "EmployeeId", "DepartmentId", });
    internal_static_com_myorg_employee_message_EmployeeDepartmentListVo_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_com_myorg_employee_message_EmployeeDepartmentListVo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_EmployeeDepartmentListVo_descriptor,
        new java.lang.String[] { "Items", "HasMore", "PagingState", });
    internal_static_com_myorg_employee_message_CreateEmployeeDepartmentCmd_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_com_myorg_employee_message_CreateEmployeeDepartmentCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_CreateEmployeeDepartmentCmd_descriptor,
        new java.lang.String[] { "EmployeeId", "DepartmentId", });
    internal_static_com_myorg_employee_message_UpdateEmployeeDepartmentCmd_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_com_myorg_employee_message_UpdateEmployeeDepartmentCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_UpdateEmployeeDepartmentCmd_descriptor,
        new java.lang.String[] { "EmployeeId", "DepartmentId", });
    internal_static_com_myorg_employee_message_DeleteEmployeeDepartmentCmd_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_com_myorg_employee_message_DeleteEmployeeDepartmentCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_DeleteEmployeeDepartmentCmd_descriptor,
        new java.lang.String[] { "EmployeeId", "DepartmentId", });
    internal_static_com_myorg_employee_message_RetrieveEmployeeDepartmentCmd_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_com_myorg_employee_message_RetrieveEmployeeDepartmentCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_myorg_employee_message_RetrieveEmployeeDepartmentCmd_descriptor,
        new java.lang.String[] { "EmployeeId", "DepartmentId", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(scalapb.options.Scalapb.options);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.TimestampProto.getDescriptor();
    scalapb.options.Scalapb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
