// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/myorg/employee/message/employee-management.proto

package com.myorg.employee.message;

public interface EmployeeDepartmentListVoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.myorg.employee.message.EmployeeDepartmentListVo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
   */
  java.util.List<com.myorg.employee.message.EmployeeDepartmentVo> 
      getItemsList();
  /**
   * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
   */
  com.myorg.employee.message.EmployeeDepartmentVo getItems(int index);
  /**
   * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
   */
  java.util.List<? extends com.myorg.employee.message.EmployeeDepartmentVoOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .com.myorg.employee.message.EmployeeDepartmentVo items = 1;</code>
   */
  com.myorg.employee.message.EmployeeDepartmentVoOrBuilder getItemsOrBuilder(
      int index);

  /**
   * <code>bool hasMore = 2;</code>
   */
  boolean getHasMore();

  /**
   * <code>string pagingState = 3;</code>
   */
  java.lang.String getPagingState();
  /**
   * <code>string pagingState = 3;</code>
   */
  com.google.protobuf.ByteString
      getPagingStateBytes();
}
