// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/myorg/employee/message/employee-management.proto

package com.myorg.employee.message;

public interface RetrieveUserCmdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.myorg.employee.message.RetrieveUserCmd)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
